services:
  make:
    build: .
    entrypoint: make
    environment:
      CI: ${CI:-false}
    privileged: true
    user: ${UID:-0}:${GID:-0}
    volumes:
    - .:/workspace
    working_dir: /workspace
