name: Build
on: workflow_dispatch
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build cloud-images
      run: |
        docker-compose run make
    - name: Upload cloud-images
      run: |
        find output -type f | xargs --replace aws s3 cp {} s3://inaccel/cloud-images/
        echo LICENSE* NOTICE* README* | xargs --max-args 1 | xargs --replace aws s3 cp {} s3://inaccel/cloud-images/
